# Generated by Django 4.0.5 on 2022-07-08 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 7, 8, 0, 0)),
        ),
    ]
