# Generated by Django 4.0.5 on 2022-07-08 23:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateField(default=datetime.datetime(2022, 7, 8, 23, 38, 8, 512902, tzinfo=utc)),
        ),
    ]
